services:
  kafka:
    image: apache/kafka-native
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: CONTROLLER://localhost:9091,HOST://0.0.0.0:9092,DOCKER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: HOST://localhost:9092,DOCKER://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,DOCKER:PLAINTEXT,HOST:PLAINTEXT

      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9091

      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
  orders-db:
    image: postgres:18-alpine
    container_name: orders-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: orders
    volumes:
      - ./orders/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
  orchestrator-db:
    image: postgres:18-alpine
    container_name: orchestrator-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: orchestrator
    volumes:
      - ./orchestrator/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"
  inventory-db:
    image: postgres:18-alpine
    container_name: inventory-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: inventory
    env_file:
      "./inventory/.env"
    volumes:
      - ./inventory/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5434:5432"
  orders:
    build:
      context: ./orders/
    container_name: orders
    ports:
      - 5000:5000
    environment:
      ASPNETCORE_URLS: http://+:5000
    depends_on:
      - kafka
  orchestrator:
    build:
      context: ./orchestrator/
    container_name: orchestrator
    depends_on:
      - kafka
  inventory:
    build:
      context: ./inventory/
    container_name: inventory
    depends_on:
      - kafka
